import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'
import ErrorBoundary from './components/ErrorBoundary.jsx'

// Apply saved BG-only mode synchronously BEFORE React renders to prevent dark flash
try {
  const ls = window.localStorage
  const earlyBg = ls.getItem('appBg') || ls.getItem('inch_app_bg')
  if (earlyBg === 'light' || earlyBg === 'dark') {
    document.documentElement.setAttribute('data-app-bg', earlyBg)
  }
} catch {}

// i18n setup
import i18next from 'i18next'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'

// Minimal resources; expand as you translate screens
const resources = {
  en: { translation: {
    Language: 'Language',
    layout: {
      brandName: 'INCH',
      brandTag: 'Tailoring SaaS',
      roleOwner: 'Business Owner 👑',
      roleStaff: 'Staff'
    },
    settings: {
      title: 'Settings',
      subtitle: 'Configure your business, account, and preferences.',
      sectionsAriaLabel: 'Settings sections',
      tabs: {
        business: 'Business',
        user: 'User Settings',
        invoice: 'Invoice',
        notifications: 'Notifications',
        security: 'Security',
        appearance: 'Appearance'
      }
    },
    business: {
      title: 'Business Information',
      subtitle: 'Manage company details and branding.',
      staffInfo: 'Only the business owner can edit these fields.',
      businessId: 'Business ID',
      businessLogo: 'Business Logo',
      uploading: 'Uploading…',
      uploadLogo: 'Upload Logo',
      businessName: 'Business Name',
      businessNamePlaceholder: 'Your business name',
      businessNameLocked: 'Business name is managed by the admin',
      ownerName: 'Owner Name',
      ownerNamePlaceholder: 'Owner full name',
      businessPhone: 'Business Phone',
      businessPhonePlaceholder: 'e.g. +1 555 123 4567',
      businessEmail: 'Business Email',
      businessEmailPlaceholder: 'name@company.com',
      businessEmailLocked: 'Business email is managed by the admin',
      businessAddress: 'Business Address',
      businessAddressPlaceholder: 'Street, City, Country',
      saveBusinessInfo: 'Save Business Info',
      saving: 'Saving…',
      savedNotice: 'Saved ✓',
      logoSaved: 'Logo updated ✓'
    },
    attendance: {
      title: 'Attendance & Shift Rules',
      subtitle: 'Define your standard workday and break policy.',
      standardShiftLength: 'Standard minutes per workday',
      maxBreaksPerDay: 'Max breaks per day',
      minutesPerBreak: 'Minutes per break',
      saveAttendanceRules: 'Save attendance rules',
      savedNotice: 'Attendance rules saved ✓'
    },
    invoice: {
      title: 'Invoice Settings',
      subtitle: 'Set invoice defaults and numbering preferences.',
      taxRate: 'Tax rate (%)',
      currency: 'Currency',
      autoGenerate: 'Automatically generate invoice numbers',
      paymentTerms: 'Payment terms',
      paymentTermsPlaceholder: 'e.g. Net 30',
      invoiceFooter: 'Invoice footer',
      invoiceFooterPlaceholder: 'Message shown at the bottom of invoices',
      saveInvoiceSettings: 'Save invoice settings'
    },
    notifications: {
      title: 'Notifications',
      subtitle: 'Choose how you want to be notified.',
      emailNotifications: 'Email notifications',
      emailNotificationsDescription: 'Receive updates and alerts via email.',
      pushNotifications: 'Push notifications',
      pushNotificationsDescription: 'Receive in-app and device push notifications.',
      saveNotificationSettings: 'Save notification preferences'
    },
    security: {
      title: 'Security',
      subtitle: 'Manage your account security and privacy.',
      accountInformation: 'Account information',
      passwordManagement: 'Password management',
      passwordManagementDescription: 'Use a strong, unique password. You can reset it here.',
      resetPassword: 'Reset password',
      downloadAccountData: 'Download account data',
      downloadAccountDataDescription: 'Export a copy of your personal data.'
    },
    appearance: {
      title: 'Appearance',
      subtitle: 'Customize theme, gradient, and glow.',
      gradientAngle: 'Gradient angle',
      gradientAngleDescription: 'Adjust the angle for the brand gradient.',
      glow: 'Glow',
      glowDescription: 'Tune the ambient glow to match your theme or pick a custom color.',
      matchTheme: 'Match theme',
      custom: 'Custom',
      depth: 'Depth',
      customGradient: 'Custom gradient',
      customGradientDescription: 'Choose your own gradient colors.',
      from: 'From',
      to: 'To',
      solidColor: 'Solid color accents',
      solidColorDescription: 'Pick a single color for solid accents.',
      themeChangesApplyInstantly: 'Theme changes apply instantly.',
      saveAppearance: 'Save appearance',
      saving: 'Saving…',
      resetToDefault: 'Reset to default',
      savedNotice: 'Saved ✓',
      saveFailed: 'Failed to save'
    },
    nav: {
      dashboard: 'Dashboard',
      customers: 'Customers',
      orders: 'Orders',
      'job cards': 'Job Cards',
      invoices: 'Invoices',
      inventory: 'Inventory',
      staff: 'Staff',
      expenses: 'Expenses',
      reports: 'Reports',
      messages: 'Messages',
      'public profile': 'Public Profile',
      settings: 'Settings'
    },
    userSettings: {
      title: 'User Settings',
      subtitle: 'Update your personal settings for this account.',
      userAvatar: 'User Avatar',
      uploading: 'Uploading…',
      uploadAvatar: 'Upload Avatar',
      displayName: 'Display Name',
      language: 'Language',
      changeEmail: 'Change Email',
      updateEmail: 'Update Email',
      newPassword: 'New Password',
      confirmPassword: 'Confirm Password',
      saving: 'Saving…',
      saveUserSettings: 'Save User Settings',
      changePassword: 'Change Password',
      placeholderName: 'Your name',
      placeholderEmail: 'you@example.com',
      savedNotice: 'Saved user settings ✓',
      emailUpdateInitiated: 'Email update initiated. Check your inbox to confirm.',
      passwordChanged: 'Password changed ✓',
      uploadAvatarSuccess: 'Avatar uploaded ✓'
    },
    common: {
      loading: 'Loading…',
      signOut: 'Sign out',
      signingOut: 'Signing out…',
      expandSidebar: 'Expand sidebar',
      collapseSidebar: 'Collapse sidebar',
      viewAll: 'View All',
      createFirstOrder: 'Create First Order',
      noOrdersYet: 'No orders yet',
      quickActions: 'Quick Actions',
      recordExpense: 'Record Expense',
      createJobCard: 'Create Job Card',
      addCustomer: 'Add Customer',
      newOrder: 'New Order',
      actions: {
        save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', update: 'Update', search: 'Search', filter: 'Filter', export: 'Export', import: 'Import', upload: 'Upload', download: 'Download', print: 'Print', apply: 'Apply', reset: 'Reset', close: 'Close', ok: 'OK', yes: 'Yes', no: 'No', add: 'Add', remove: 'Remove'
      },
      feedback: {
        saved: 'Saved ✓', updated: 'Updated ✓', deleted: 'Deleted ✓', errorSaving: 'Error saving', errorLoading: 'Error loading', areYouSure: 'Are you sure?', confirmDelete: 'Confirm delete?', required: 'Required field', invalidEmail: 'Invalid email'
      }
    },
    dashboard: {
      lowStockAlerts: 'Low Stock Alerts',
      allFabricsStocked: 'All fabrics are well stocked',
      viewInventory: 'View Inventory',
      recentOrders: 'Recent Orders',
      todaysActivity: "Today's Activity",
      nowOrders: 'Now Orders',
      ordersReady: 'Orders Ready',
      inProgress: 'In Progress',
      totalRevenue: 'Total Revenue',
      totalCustomers: 'Total Customers',
      totalOrders: 'Total Orders',
      lowStockItems: 'Low Stock Items',
      pendingOrders: 'Pending Orders',
      businessBadge: 'Business',
      idLabel: 'ID',
      welcomeToBrand: 'Welcome to INCH',
      welcomeBusinessToBrand: 'Welcome {{name}} to INCH',
      staffId: 'StaffID'
    },
    customers: {
      title: 'Customers',
      subtitle: 'Manage your customers.',
      searchPlaceholder: 'Search name or phone…',
      addCustomer: '+ Add Customer',
      loading: 'Loading…',
      empty: 'No customers found',
      modal: { addTitle: 'Add Customer', editTitle: 'Edit Customer', close: 'Close' },
      form: {
        basics: 'Basics',
        name: 'Name', phone: 'Phone', email: 'Email', address: 'Address',
        nameRequired: 'Name is required',
        nameTooShort: 'Name must be at least 2 characters',
        phoneRequired: 'Phone is required',
        invalidEmail: 'Invalid email',
        measurements: 'Measurements',
        visualMeasurements: 'Visual Measurements',
        addLabel: 'Add label', moveBuiltIns: 'Move built-ins', clearCustomLabels: 'Clear custom labels',
        customMeasurements: 'Custom measurements', add: '+ Add', remove: 'Remove',
        value: 'Value', unit: 'Unit', cm: 'cm', inch: 'in',
        measure: { chest: 'Chest', waist: 'Waist', hips: 'Hips', shoulders: 'Shoulders', sleeve_length: 'Sleeve length', neck: 'Neck', inseam: 'Inseam', outseam: 'Outseam', thigh: 'Thigh' },
        preferences: 'Preferences', preferredFabric: 'Preferred Fabric', styleNotes: 'Style Notes', specialRequirements: 'Special Requirements',
        cancel: 'Cancel', saving: 'Saving…', saveChanges: 'Save Changes', createCustomer: 'Create Customer'
      },
      card: {
        created: 'Created',
        orders: 'Orders',
        spent: 'Spent',
        last: 'Last',
        edit: 'Edit'
      }
    }
  } },
  ar: { translation: {
    Language: 'اللغة',
    layout: {
      brandName: 'INCH',
      brandTag: 'منصة تفصيل',
      roleOwner: 'مالك العمل 👑',
      roleStaff: 'موظف'
    },
    nav: {
      dashboard: 'لوحة التحكم',
      customers: 'العملاء',
      orders: 'الطلبيات',
      'job cards': 'بطاقات العمل',
      invoices: 'الفواتير',
      inventory: 'المخزون',
      staff: 'الموظفون',
      expenses: 'المصروفات',
      reports: 'التقارير',
      messages: 'الرسائل',
      'public profile': 'الملف العام',
      settings: 'الإعدادات'
    },
    settings: {
      title: 'الإعدادات',
      subtitle: 'اضبط معلومات عملك وحسابك وتفضيلاتك.',
      sectionsAriaLabel: 'أقسام الإعدادات',
      tabs: { business: 'الأعمال', user: 'إعدادات المستخدم', invoice: 'الفواتير', notifications: 'الإشعارات', security: 'الأمان', appearance: 'المظهر' }
    },
    business: {
      title: 'معلومات العمل',
      subtitle: 'إدارة تفاصيل الشركة والعلامة.',
      staffInfo: 'يمكن لمالك العمل فقط تعديل هذه الحقول.',
      businessId: 'معرّف العمل',
      businessLogo: 'شعار العمل',
      uploading: 'جارٍ الرفع…',
      uploadLogo: 'رفع الشعار',
      businessName: 'اسم العمل',
      businessNamePlaceholder: 'اسم شركتك',
      businessNameLocked: 'اسم العمل يدار من قبل المسؤول',
      ownerName: 'اسم المالك',
      ownerNamePlaceholder: 'الاسم الكامل للمالك',
      businessPhone: 'هاتف العمل',
      businessPhonePlaceholder: 'مثال: +965 555 12345',
      businessEmail: 'بريد العمل',
      businessEmailPlaceholder: 'name@company.com',
      businessEmailLocked: 'بريد العمل يدار من قبل المسؤول',
      businessAddress: 'عنوان العمل',
      businessAddressPlaceholder: 'الشارع، المدينة، الدولة',
      saveBusinessInfo: 'حفظ معلومات العمل',
      saving: 'جارٍ الحفظ…',
      savedNotice: 'تم الحفظ ✓',
      logoSaved: 'تم تحديث الشعار ✓'
    },
    attendance: {
      title: 'الحضور وقواعد الدوام',
      subtitle: 'عيّن يوم العمل القياسي وسياسة الاستراحة.',
      standardShiftLength: 'الدقائق القياسية لليوم',
      maxBreaksPerDay: 'أقصى عدد للاستراحات يوميًا',
      minutesPerBreak: 'الدقائق لكل استراحة',
      saveAttendanceRules: 'حفظ قواعد الحضور',
      savedNotice: 'تم حفظ قواعد الحضور ✓'
    },
    invoice: {
      title: 'إعدادات الفاتورة',
      subtitle: 'تعيين الإعدادات الافتراضية للفاتورة.',
      taxRate: 'نسبة الضريبة (%)',
      currency: 'العملة',
      autoGenerate: 'توليد أرقام الفواتير تلقائيًا',
      paymentTerms: 'شروط الدفع',
      paymentTermsPlaceholder: 'مثال: صافي 30',
      invoiceFooter: 'تذييل الفاتورة',
      invoiceFooterPlaceholder: 'رسالة تظهر أسفل الفاتورة',
      saveInvoiceSettings: 'حفظ إعدادات الفاتورة'
    },
    notifications: {
      title: 'الإشعارات',
      subtitle: 'اختر طريقة استلام التنبيهات.',
      emailNotifications: 'إشعارات البريد الإلكتروني',
      emailNotificationsDescription: 'استلام التحديثات والتنبيهات عبر البريد.',
      pushNotifications: 'إشعارات الدفع',
      pushNotificationsDescription: 'استلام إشعارات داخل التطبيق وعلى الجهاز.',
      saveNotificationSettings: 'حفظ تفضيلات الإشعارات'
    },
    security: {
      title: 'الأمان',
      subtitle: 'إدارة أمان الحساب والخصوصية.',
      accountInformation: 'معلومات الحساب',
      passwordManagement: 'إدارة كلمة المرور',
      passwordManagementDescription: 'استخدم كلمة مرور قوية وفريدة. يمكنك إعادة تعيينها هنا.',
      resetPassword: 'إعادة تعيين كلمة المرور',
      downloadAccountData: 'تنزيل بيانات الحساب',
      downloadAccountDataDescription: 'تصدير نسخة من بياناتك الشخصية.'
    },
    appearance: {
      title: 'المظهر',
      subtitle: 'خصّص السمة والتدرج والتوهج.',
      gradientAngle: 'زاوية التدرج',
      gradientAngleDescription: 'اضبط زاوية التدرج اللوني.',
      glow: 'التوهج',
      glowDescription: 'اضبط التوهج ليتطابق مع السمة أو اختر لونًا مخصصًا.',
      matchTheme: 'مطابقة السمة',
      custom: 'مخصص',
      depth: 'العمق',
      customGradient: 'تدرج مخصص',
      customGradientDescription: 'اختر ألوان التدرج الخاصة بك.',
      from: 'من',
      to: 'إلى',
      solidColor: 'ألوان ثابتة',
      solidColorDescription: 'اختر لونًا واحدًا للعناصر الثابتة.',
      themeChangesApplyInstantly: 'تُطبّق تغييرات السمة فورًا.',
      saveAppearance: 'حفظ المظهر',
      saving: 'جارٍ الحفظ…',
      resetToDefault: 'إعادة التعيين للوضع الافتراضي',
      savedNotice: 'تم الحفظ ✓',
      saveFailed: 'فشل الحفظ'
    },
    userSettings: {
      title: 'إعدادات المستخدم',
      subtitle: 'حدِّث إعداداتك الشخصية لهذا الحساب.',
      userAvatar: 'صورة المستخدم',
      uploading: 'جارٍ الرفع…',
      uploadAvatar: 'رفع الصورة',
      displayName: 'الاسم المعروض',
      language: 'اللغة',
      changeEmail: 'تغيير البريد الإلكتروني',
      updateEmail: 'تحديث البريد الإلكتروني',
      newPassword: 'كلمة مرور جديدة',
      confirmPassword: 'تأكيد كلمة المرور',
      saving: 'جارٍ الحفظ…',
      saveUserSettings: 'حفظ إعدادات المستخدم',
      changePassword: 'تغيير كلمة المرور',
      placeholderName: 'اسمك',
      placeholderEmail: 'you@example.com',
      savedNotice: 'تم حفظ إعدادات المستخدم ✓',
      emailUpdateInitiated: 'تم بدء تحديث البريد الإلكتروني. تحقّق من بريدك لتأكيد العملية.',
      passwordChanged: 'تم تغيير كلمة المرور ✓',
      uploadAvatarSuccess: 'تم رفع الصورة ✓'
    },
    common: {
      loading: 'جارٍ التحميل…',
      signOut: 'تسجيل الخروج',
      signingOut: 'جارٍ تسجيل الخروج…',
      expandSidebar: 'توسيع الشريط الجانبي',
      collapseSidebar: 'طي الشريط الجانبي',
      viewAll: 'عرض الكل',
      createFirstOrder: 'إنشاء أول طلب',
      noOrdersYet: 'لا توجد طلبات بعد',
      quickActions: 'إجراءات سريعة',
      recordExpense: 'تسجيل مصروف',
      createJobCard: 'إنشاء بطاقة عمل',
      addCustomer: 'إضافة عميل',
      newOrder: 'طلب جديد',
      actions: { save: 'حفظ', cancel: 'إلغاء', edit: 'تعديل', delete: 'حذف', update: 'تحديث', search: 'بحث', filter: 'تصفية', export: 'تصدير', import: 'استيراد', upload: 'رفع', download: 'تنزيل', print: 'طباعة', apply: 'تطبيق', reset: 'إعادة تعيين', close: 'إغلاق', ok: 'حسناً', yes: 'نعم', no: 'لا', add: 'إضافة', remove: 'إزالة' },
      feedback: { saved: 'تم الحفظ ✓', updated: 'تم التحديث ✓', deleted: 'تم الحذف ✓', errorSaving: 'خطأ في الحفظ', errorLoading: 'خطأ في التحميل', areYouSure: 'هل أنت متأكد؟', confirmDelete: 'تأكيد الحذف؟', required: 'حقل مطلوب', invalidEmail: 'بريد غير صالح' }
    },
    dashboard: {
      lowStockAlerts: 'تنبيهات انخفاض المخزون',
      allFabricsStocked: 'جميع الأقمشة متوفرة',
      viewInventory: 'عرض المخزون',
      recentOrders: 'الطلبات الحديثة',
      todaysActivity: 'نشاط اليوم',
      nowOrders: 'طلبات الآن',
      ordersReady: 'طلبات جاهزة',
      inProgress: 'قيد الإنجاز',
      totalRevenue: 'إجمالي الإيرادات',
      totalCustomers: 'إجمالي العملاء',
      totalOrders: 'إجمالي الطلبات',
      lowStockItems: 'أصناف منخفضة المخزون',
      pendingOrders: 'طلبات قيد الانتظار',
      businessBadge: 'العمل',
      idLabel: 'المعرّف',
      welcomeToBrand: 'مرحباً بك في INCH',
      welcomeBusinessToBrand: 'مرحباً {{name}} في INCH',
      staffId: 'معرّف الموظف'
    },
    customers: {
      title: 'العملاء',
      subtitle: 'إدارة العملاء.',
      searchPlaceholder: 'ابحث بالاسم أو الهاتف…',
      addCustomer: '+ إضافة عميل',
      loading: 'جارٍ التحميل…',
      empty: 'لا يوجد عملاء',
      modal: { addTitle: 'إضافة عميل', editTitle: 'تعديل العميل', close: 'إغلاق' },
      form: { basics: 'الأساسيات', name: 'الاسم', phone: 'الهاتف', email: 'البريد الإلكتروني', address: 'العنوان', nameRequired: 'الاسم مطلوب', nameTooShort: 'يجب أن لا يقل الاسم عن حرفين', phoneRequired: 'الهاتف مطلوب', invalidEmail: 'بريد غير صالح', measurements: 'القياسات', visualMeasurements: 'قياسات مرئية', addLabel: 'إضافة تسمية', moveBuiltIns: 'تحريك الافتراضية', clearCustomLabels: 'مسح التسميات المخصصة', customMeasurements: 'قياسات مخصصة', add: '+ إضافة', remove: 'إزالة', value: 'القيمة', unit: 'الوحدة', cm: 'سم', inch: 'إنش', measure: { chest: 'الصدر', waist: 'الخصر', hips: 'الورك', shoulders: 'الأكتاف', sleeve_length: 'طول الكم', neck: 'العنق', inseam: 'الطول الداخلي', outseam: 'الطول الخارجي', thigh: 'الفخذ' }, preferences: 'التفضيلات', preferredFabric: 'القماش المفضل', styleNotes: 'ملاحظات التصميم', specialRequirements: 'متطلبات خاصة', cancel: 'إلغاء', saving: 'جارٍ الحفظ…', saveChanges: 'حفظ التغييرات', createCustomer: 'إنشاء عميل' },
      card: { created: 'تاريخ الإنشاء', orders: 'الطلبات', spent: 'المصروف', last: 'آخر', edit: 'تعديل' }
    }
  } },
  hi: { translation: {
    Language: 'भाषा',
    layout: {
      brandName: 'INCH',
      brandTag: 'टेलरिंग SaaS',
      roleOwner: 'व्यवसाय मालिक 👑',
      roleStaff: 'स्टाफ'
    },
    nav: {
      dashboard: 'डैशबोर्ड',
      customers: 'ग्राहक',
      orders: 'ऑर्डर',
      'job cards': 'जॉब कार्ड्स',
      invoices: 'इनवॉइस',
      inventory: 'इन्वेंटरी',
      staff: 'स्टाफ',
      expenses: 'खर्चे',
      reports: 'रिपोर्ट्स',
      messages: 'संदेश',
      'public profile': 'सार्वजनिक प्रोफ़ाइल',
      settings: 'सेटिंग्स'
    },
    settings: { title: 'सेटिंग्स', subtitle: 'अपने व्यवसाय, खाता और वरीयताएँ कॉन्फ़िगर करें।', sectionsAriaLabel: 'सेटिंग्स सेक्शन', tabs: { business: 'बिज़नेस', user: 'यूज़र सेटिंग्स', invoice: 'इनवॉइस', notifications: 'नोटिफ़िकेशन', security: 'सुरक्षा', appearance: 'दिखावट' } },
    business: { title: 'बिज़नेस जानकारी', subtitle: 'कंपनी विवरण और ब्रांडिंग प्रबंधित करें।', staffInfo: 'केवल मालिक इन फ़ील्ड्स को संपादित कर सकता है।', businessId: 'बिज़नेस आईडी', businessLogo: 'बिज़नेस लोगो', uploading: 'अपलोड हो रहा है…', uploadLogo: 'लोगो अपलोड करें', businessName: 'बिज़नेस नाम', businessNamePlaceholder: 'आपके व्यवसाय का नाम', businessNameLocked: 'बिज़नेस नाम एडमिन द्वारा नियंत्रित है', ownerName: 'मालिक का नाम', ownerNamePlaceholder: 'पूरा नाम', businessPhone: 'बिज़नेस फोन', businessPhonePlaceholder: 'उदा. +91 90000 00000', businessEmail: 'बिज़नेस ईमेल', businessEmailPlaceholder: 'name@company.com', businessEmailLocked: 'बिज़नेस ईमेल एडमिन द्वारा नियंत्रित है', businessAddress: 'बिज़नेस पता', businessAddressPlaceholder: 'गली, शहर, देश', saveBusinessInfo: 'बिज़नेस जानकारी सहेजें', saving: 'सहेजा जा रहा है…', savedNotice: 'सहेजा गया ✓', logoSaved: 'लोगो अपडेट हुआ ✓' },
    attendance: { title: 'उपस्थिति और शिफ्ट नियम', subtitle: 'मानक कार्य-दिन और ब्रेक नीति तय करें।', standardShiftLength: 'प्रति दिन मानक मिनट', maxBreaksPerDay: 'प्रति दिन अधिकतम ब्रेक', minutesPerBreak: 'प्रति ब्रेक मिनट', saveAttendanceRules: 'उपस्थिति नियम सहेजें', savedNotice: 'उपस्थिति नियम सहेजे गए ✓' },
    invoice: { title: 'इनवॉइस सेटिंग्स', subtitle: 'इनवॉइस डिफ़ॉल्ट और नंबरिंग सेट करें।', taxRate: 'टैक्स दर (%)', currency: 'मुद्रा', autoGenerate: 'इनवॉइस नंबर स्वतः बनाएं', paymentTerms: 'भुगतान शर्तें', paymentTermsPlaceholder: 'उदा. नेट 30', invoiceFooter: 'इनवॉइस फुटर', invoiceFooterPlaceholder: 'इनवॉइस के नीचे दिखने वाला संदेश', saveInvoiceSettings: 'इनवॉइस सेटिंग्स सहेजें' },
    notifications: { title: 'नोटिफ़िकेशन', subtitle: 'आप कैसे सूचित होना चाहते हैं चुनें।', emailNotifications: 'ईमेल नोटिफ़िकेशन', emailNotificationsDescription: 'ईमेल द्वारा अपडेट और अलर्ट प्राप्त करें।', pushNotifications: 'पुश नोटिफ़िकेशन', pushNotificationsDescription: 'ऐप और डिवाइस पर पुश अलर्ट प्राप्त करें।', saveNotificationSettings: 'नोटिफ़िकेशन वरीयताएँ सहेजें' },
    security: { title: 'सुरक्षा', subtitle: 'खाता सुरक्षा और गोपनीयता प्रबंधित करें।', accountInformation: 'खाता जानकारी', passwordManagement: 'पासवर्ड प्रबंधन', passwordManagementDescription: 'मजबूत, यूनिक पासवर्ड रखें। यहाँ रीसेट कर सकते हैं।', resetPassword: 'पासवर्ड रीसेट', downloadAccountData: 'खाता डेटा डाउनलोड', downloadAccountDataDescription: 'अपना व्यक्तिगत डेटा निर्यात करें।' },
    appearance: { title: 'दिखावट', subtitle: 'थीम, ग्रेडिएंट और ग्लो को कस्टमाइज़ करें।', gradientAngle: 'ग्रेडिएंट कोण', gradientAngleDescription: 'ब्रांड ग्रेडिएंट का कोण समायोजित करें।', glow: 'ग्लो', glowDescription: 'थीम से मैच करें या कस्टम रंग चुनें।', matchTheme: 'थीम से मैच', custom: 'कस्टम', depth: 'गहराई', customGradient: 'कस्टम ग्रेडिएंट', customGradientDescription: 'अपने रंग चुनें।', from: 'से', to: 'तक', solidColor: 'सॉलिड रंग एक्सेंट', solidColorDescription: 'एकल रंग चुनें।', themeChangesApplyInstantly: 'थीम परिवर्तन तुरंत लागू होते हैं।', saveAppearance: 'दिखावट सहेजें', saving: 'सहेजा जा रहा है…', resetToDefault: 'डिफ़ॉल्ट पर रीसेट', savedNotice: 'सहेजा गया ✓', saveFailed: 'सहेजने में विफल' },
    userSettings: {
      title: 'उपयोगकर्ता सेटिंग्स',
      subtitle: 'इस खाते के लिए अपनी व्यक्तिगत सेटिंग्स अपडेट करें।',
      userAvatar: 'उपयोगकर्ता अवतार',
      uploading: 'अपलोड हो रहा है…',
      uploadAvatar: 'अवतार अपलोड करें',
      displayName: 'प्रदर्शित नाम',
      language: 'भाषा',
      changeEmail: 'ईमेल बदलें',
      updateEmail: 'ईमेल अपडेट करें',
      newPassword: 'नया पासवर्ड',
      confirmPassword: 'पासवर्ड की पुष्टि करें',
      saving: 'सहेजा जा रहा है…',
      saveUserSettings: 'उपयोगकर्ता सेटिंग्स सहेजें',
      changePassword: 'पासवर्ड बदलें',
      placeholderName: 'आपका नाम',
      placeholderEmail: 'you@example.com',
      savedNotice: 'उपयोगकर्ता सेटिंग्स सहेजी गईं ✓',
      emailUpdateInitiated: 'ईमेल अपडेट शुरू किया गया। पुष्टि के लिए अपना इनबॉक्स जांचें।',
      passwordChanged: 'पासवर्ड बदल दिया गया ✓',
      uploadAvatarSuccess: 'अवतार अपलोड हो गया ✓'
    },
    common: {
      loading: 'लोड हो रहा है…',
      signOut: 'साइन आउट',
      signingOut: 'साइन आउट हो रहा है…',
      expandSidebar: 'साइडबार बढ़ाएँ',
      collapseSidebar: 'साइडबार संक्षिप्त करें',
      viewAll: 'सभी देखें',
      createFirstOrder: 'पहला ऑर्डर बनाएं',
      noOrdersYet: 'अभी कोई ऑर्डर नहीं',
      quickActions: 'त्वरित क्रियाएँ',
      recordExpense: 'खर्च रिकॉर्ड करें',
      createJobCard: 'जॉब कार्ड बनाएं',
      addCustomer: 'ग्राहक जोड़ें',
      newOrder: 'नया ऑर्डर',
      actions: { save: 'सहेजें', cancel: 'रद्द करें', edit: 'संपादित करें', delete: 'हटाएं', update: 'अपडेट करें', search: 'खोजें', filter: 'फ़िल्टर', export: 'निर्यात', import: 'आयात', upload: 'अपलोड', download: 'डाउनलोड', print: 'प्रिंट', apply: 'लागू करें', reset: 'रीसेट', close: 'बंद करें', ok: 'ठीक', yes: 'हाँ', no: 'नहीं', add: 'जोड़ें', remove: 'हटाएं' },
      feedback: { saved: 'सहेजा गया ✓', updated: 'अपडेट किया गया ✓', deleted: 'हटा दिया गया ✓', errorSaving: 'सहेजने में त्रुटि', errorLoading: 'लोड करने में त्रुटि', areYouSure: 'क्या आप सुनिश्चित हैं?', confirmDelete: 'हटाने की पुष्टि?', required: 'आवश्यक फ़ील्ड', invalidEmail: 'अमान्य ईमेल' }
    },
    dashboard: {
      lowStockAlerts: 'कम स्टॉक अलर्ट',
      allFabricsStocked: 'सभी फैब्रिक स्टॉक में हैं',
      viewInventory: 'इन्वेंटरी देखें',
      recentOrders: 'हाल के ऑर्डर',
      todaysActivity: 'आज की गतिविधि',
      nowOrders: 'अभी के ऑर्डर',
      ordersReady: 'ऑर्डर तैयार',
      inProgress: 'प्रगति पर',
      totalRevenue: 'कुल राजस्व',
      totalCustomers: 'कुल ग्राहक',
      totalOrders: 'कुल ऑर्डर',
      lowStockItems: 'कम स्टॉक आइटम',
      pendingOrders: 'लंबित ऑर्डर',
      businessBadge: 'व्यवसाय',
      idLabel: 'आईडी',
      welcomeToBrand: 'INCH में आपका स्वागत है',
      welcomeBusinessToBrand: 'स्वागत है {{name}} INCH में',
      staffId: 'स्टाफ आईडी'
    },
    customers: {
      title: 'ग्राहक',
      subtitle: 'अपने ग्राहकों का प्रबंधन करें।',
      searchPlaceholder: 'नाम या फोन से खोजें…',
      addCustomer: '+ ग्राहक जोड़ें',
      loading: 'लोड हो रहा है…',
      empty: 'कोई ग्राहक नहीं मिला',
      modal: { addTitle: 'ग्राहक जोड़ें', editTitle: 'ग्राहक संपादित करें', close: 'बंद करें' },
      form: { basics: 'मूल विवरण', name: 'नाम', phone: 'फोन', email: 'ईमेल', address: 'पता', nameRequired: 'नाम आवश्यक है', nameTooShort: 'नाम कम से कम 2 अक्षरों का होना चाहिए', phoneRequired: 'फोन आवश्यक है', invalidEmail: 'अमान्य ईमेल', measurements: 'माप', visualMeasurements: 'दृश्य माप', addLabel: 'लेबल जोड़ें', moveBuiltIns: 'बिल्ट-इन स्थानांतरित करें', clearCustomLabels: 'कस्टम लेबल साफ करें', customMeasurements: 'कस्टम माप', add: '+ जोड़ें', remove: 'हटाएं', value: 'मान', unit: 'इकाई', cm: 'सेमी', inch: 'इंच', measure: { chest: 'छाती', waist: 'कमर', hips: 'कूल्हे', shoulders: 'कंधे', sleeve_length: 'आस्तीन की लंबाई', neck: 'गला', inseam: 'इनसीम', outseam: 'आउटसीम', thigh: 'जांघ' }, preferences: 'पसंद', preferredFabric: 'पसंदीदा कपड़ा', styleNotes: 'स्टाइल नोट्स', specialRequirements: 'विशेष आवश्यकताएं', cancel: 'रद्द करें', saving: 'सहेजा जा रहा है…', saveChanges: 'परिवर्तन सहेजें', createCustomer: 'ग्राहक बनाएँ' },
      card: { created: 'निर्मित', orders: 'ऑर्डर', spent: 'खर्च', last: 'अंतिम', edit: 'संपादित करें' }
    }
  } },
  ne: { translation: {
    Language: 'भाषा',
    layout: {
      brandName: 'INCH', brandTag: 'टेलरिङ SaaS', roleOwner: 'व्यवसाय मालिक 👑', roleStaff: 'स्टाफ'
    },
    nav: {
      dashboard: 'ड्यासबोर्ड', customers: 'ग्राहक', orders: 'अर्डर', 'job cards': 'जव कार्ड', invoices: 'चलानी', inventory: 'भण्डार', staff: 'स्टाफ', expenses: 'खर्च', reports: 'प्रतिवेदन', messages: 'सन्देश', 'public profile': 'सार्वजनिक प्रोफाइल', settings: 'सेटिङ्स'
    },
    settings: { title: 'सेटिङ्स', subtitle: 'व्यवसाय, खाता र प्राथमिकताहरू मिलाउनुहोस्।', sectionsAriaLabel: 'सेटिङ्स भागहरू', tabs: { business: 'बिजनेस', user: 'प्रयोगकर्ता सेटिङ', invoice: 'चलानी', notifications: 'सूचनाहरू', security: 'सुरक्षा', appearance: 'दृश्य' } },
    business: { title: 'बिजनेस जानकारी', subtitle: 'कम्पनी विवरण र ब्रान्ड व्यवस्थापन।', staffInfo: 'यी फाँटाहरू मालिकले मात्र सम्पादन गर्न सक्छ।', businessId: 'बिजनेस आईडी', businessLogo: 'बिजनेस लोगो', uploading: 'अपलोड हुँदै…', uploadLogo: 'लोगो अपलोड', businessName: 'बिजनेस नाम', businessNamePlaceholder: 'तपाईंको व्यवसायको नाम', businessNameLocked: 'बिजनेस नाम व्यवस्थापकले नियन्त्रण गर्छ', ownerName: 'मालिकको नाम', ownerNamePlaceholder: 'पूरा नाम', businessPhone: 'बिजनेस फोन', businessPhonePlaceholder: 'जस्तै +977 9800000000', businessEmail: 'बिजनेस इमेल', businessEmailPlaceholder: 'name@company.com', businessEmailLocked: 'इमेल व्यवस्थापकले नियन्त्रण गर्छ', businessAddress: 'बिजनेस ठेगाना', businessAddressPlaceholder: 'गल्ली, सहर, देश', saveBusinessInfo: 'बिजनेस जानकारी सेभ', saving: 'सेभ हुँदै…', savedNotice: 'सेभ भयो ✓', logoSaved: 'लोगो अपडेट भयो ✓' },
    attendance: { title: 'हाजिरी र सिफ्ट नियम', subtitle: 'मानक कार्य-दिन र ब्रेक नीति निर्धारण गर्नुहोस्।', standardShiftLength: 'दिनको मानक मिनेट', maxBreaksPerDay: 'प्रतिदिन अधिकतम ब्रेक', minutesPerBreak: 'प्रत्येक ब्रेकका मिनेट', saveAttendanceRules: 'हाजिरी नियम सेभ', savedNotice: 'हाजिरी नियम सेभ भयो ✓' },
    invoice: { title: 'चलानी सेटिङ', subtitle: 'चलानीका पूर्वनिर्धारित सेटिङहरू राख्नुहोस्।', taxRate: 'कर दर (%)', currency: 'मुद्रा', autoGenerate: 'चलानी नम्बर स्वतः बनाउने', paymentTerms: 'भुक्तानी सर्तहरू', paymentTermsPlaceholder: 'उदा. नेट 30', invoiceFooter: 'चलानी फूटर', invoiceFooterPlaceholder: 'चलानीको तल देखिने सन्देश', saveInvoiceSettings: 'चलानी सेटिङ सेभ' },
    notifications: { title: 'सूचनाहरू', subtitle: 'सूचनाहरू कसरी पाउने?', emailNotifications: 'इमेल सूचनाहरू', emailNotificationsDescription: 'इमेलमार्फत अपडेटहरू प्राप्त गर्नुहोस्।', pushNotifications: 'पुश सूचनाहरू', pushNotificationsDescription: 'एप र डिभाइसमा पुश अलर्ट प्राप्त गर्नुहोस्।', saveNotificationSettings: 'सूचना प्राथमिकता सेभ' },
    security: { title: 'सुरक्षा', subtitle: 'खाता सुरक्षा र गोपनीयता व्यवस्थापन।', accountInformation: 'खाता जानकारी', passwordManagement: 'पासवर्ड व्यवस्थापन', passwordManagementDescription: 'बलियो र अद्वितीय पासवर्ड प्रयोग गर्नुहोस्।', resetPassword: 'पासवर्ड रिसेट', downloadAccountData: 'खाता डाटा डाउनलोड', downloadAccountDataDescription: 'आफ्नो व्यक्तिगत डाटा निर्यात गर्नुहोस्।' },
    appearance: { title: 'दृश्य', subtitle: 'थिम, ग्रेडिएन्ट र ग्लो मिलाउनुहोस्।', gradientAngle: 'ग्रेडिएन्ट कोण', gradientAngleDescription: 'ब्रान्ड ग्रेडिएन्टको कोण समायोजन गर्नुहोस्।', glow: 'ग्लो', glowDescription: 'थिमसँग मिलाउनुहोस् वा कस्टम रंग छान्नुहोस्।', matchTheme: 'थिमसँग मिलान', custom: 'कस्टम', depth: 'गहिराइ', customGradient: 'कस्टम ग्रेडिएन्ट', customGradientDescription: 'आफ्नै रङ छान्नुहोस्।', from: 'बाट', to: 'सम्म', solidColor: 'ठोस रङ एक्सेन्ट', solidColorDescription: 'एउटा रङ छान्नुहोस्।', themeChangesApplyInstantly: 'थिम परिवर्तन तुरुन्त लागू हुन्छ।', saveAppearance: 'दृश्य सेभ', saving: 'सेभ हुँदै…', resetToDefault: 'डिफल्टमा फर्काउनुहोस्', savedNotice: 'सेभ भयो ✓', saveFailed: 'सेभ असफल' },
    userSettings: {
      title: 'प्रयोगकर्ता सेटिङ',
      subtitle: 'यस खाताको लागि आफ्ना व्यक्तिगत सेटिङहरू अपडेट गर्नुहोस्।',
      userAvatar: 'प्रयोगकर्ता अवतार',
      uploading: 'अपलोड हुँदै…',
      uploadAvatar: 'अवतार अपलोड गर्नुहोस्',
      displayName: 'प्रदर्शित नाम',
      language: 'भाषा',
      changeEmail: 'इमेल परिवर्तन गर्नुहोस्',
      updateEmail: 'इमेल अपडेट गर्नुहोस्',
      newPassword: 'नयाँ पासवर्ड',
      confirmPassword: 'पासवर्ड पुष्टि गर्नुहोस्',
      saving: 'सेभ हुँदै…',
      saveUserSettings: 'प्रयोगकर्ता सेटिङ सेभ गर्नुहोस्',
      changePassword: 'पासवर्ड परिवर्तन गर्नुहोस्',
      placeholderName: 'तपाईंको नाम',
      placeholderEmail: 'you@example.com',
      savedNotice: 'प्रयोगकर्ता सेटिङ सेभ भयो ✓',
      emailUpdateInitiated: 'इमेल अपडेट सुरु भयो। पुष्टि गर्न इनबक्स जाँच गर्नुहोस्।',
      passwordChanged: 'पासवर्ड परिवर्तन भयो ✓',
      uploadAvatarSuccess: 'अवतार अपलोड भयो ✓'
    },
    common: {
      loading: 'लोड हुँदै…',
      signOut: 'साइन आउट',
      signingOut: 'साइन आउट हुँदै…',
      expandSidebar: 'साइडबार बढाउनुहोस्',
      collapseSidebar: 'साइडबार घटाउनुहोस्',
      viewAll: 'सबै हेर्नुहोस्',
      createFirstOrder: 'पहिलो अर्डर बनाउनुहोस्',
      noOrdersYet: 'अहिलेसम्म अर्डर छैन',
      quickActions: 'छिटो कार्य',
      recordExpense: 'खर्च रेकर्ड गर्नुहोस्',
      createJobCard: 'जव कार्ड बनाउनुहोस्',
      addCustomer: 'ग्राहक थप्नुहोस्',
      newOrder: 'नयाँ अर्डर',
      actions: { save: 'सेभ', cancel: 'रद्द', edit: 'सम्पादन', delete: 'हटाउनुहोस्', update: 'अपडेट', search: 'खोज', filter: 'फिल्टर', export: 'निर्यात', import: 'आयात', upload: 'अपलोड', download: 'डाउनलोड', print: 'प्रिन्ट', apply: 'लागू', reset: 'रिसेट', close: 'बन्द', ok: 'ठिक', yes: 'हो', no: 'होइन', add: 'थप्नुहोस्', remove: 'हटाउनुहोस्' },
      feedback: { saved: 'सेभ भयो ✓', updated: 'अपडेट भयो ✓', deleted: 'हटाइयो ✓', errorSaving: 'सेभ गर्न त्रुटि', errorLoading: 'लोड गर्न त्रुटि', areYouSure: 'पक्का?', confirmDelete: 'हटाउन पुष्टि?', required: 'आवश्यक फाँट', invalidEmail: 'अमान्य इमेल' }
    },
    dashboard: {
      lowStockAlerts: 'कम स्टक सूचना',
      allFabricsStocked: 'सबै कपडा उपलब्ध छन्',
      viewInventory: 'भण्डार हेर्नुहोस्',
      recentOrders: 'हालका अर्डर',
      todaysActivity: 'आजको गतिविधि',
      nowOrders: 'हालका अर्डर',
      ordersReady: 'अर्डर तयार',
      inProgress: 'प्रगतिमा',
      totalRevenue: 'कुल आम्दानी',
      totalCustomers: 'कुल ग्राहक',
      totalOrders: 'कुल अर्डर',
      lowStockItems: 'कम स्टक वस्तु',
      pendingOrders: 'विचाराधीन अर्डर',
      businessBadge: 'व्यवसाय',
      idLabel: 'आईडी',
      welcomeToBrand: 'INCH मा स्वागत छ',
      welcomeBusinessToBrand: 'स्वागत छ {{name}} INCH मा',
      staffId: 'स्टाफ आईडी'
    },
    customers: {
      title: 'ग्राहक',
      subtitle: 'तपाईंका ग्राहकहरू व्यवस्थापन गर्नुहोस्।',
      searchPlaceholder: 'नाम वा फोन खोज्नुहोस्…',
      addCustomer: '+ ग्राहक थप्नुहोस्',
      loading: 'लोड हुँदै…',
      empty: 'ग्राहक भेटिएन',
      modal: { addTitle: 'ग्राहक थप्नुहोस्', editTitle: 'ग्राहक सम्पादन', close: 'बन्द' },
      form: { basics: 'आधारभूत', name: 'नाम', phone: 'फोन', email: 'इमेल', address: 'ठेगाना', nameRequired: 'नाम आवश्यक छ', nameTooShort: 'नाम कम्तीमा २ अक्षरको हुनुपर्छ', phoneRequired: 'फोन आवश्यक छ', invalidEmail: 'अवैध इमेल', measurements: 'मापन', visualMeasurements: 'दृश्य मापन', addLabel: 'लेबल थप्नुहोस्', moveBuiltIns: 'बिल्ट-इन सार्नुहोस्', clearCustomLabels: 'कस्टम लेबल हटाउनुहोस्', customMeasurements: 'कस्टम मापन', add: '+ थप्नुहोस्', remove: 'हटाउनुहोस्', value: 'मान', unit: 'एकाइ', cm: 'सेमी', inch: 'इन्च', measure: { chest: 'छाती', waist: 'कम्मर', hips: 'हिप्स', shoulders: 'काध', sleeve_length: 'बाहुको लम्बाइ', neck: 'घाँटी', inseam: 'इनसिम', outseam: 'आउटसिम', thigh: 'जाङ्ग' }, preferences: 'रूचि', preferredFabric: 'मनपर्ने कपडा', styleNotes: 'शैली टिप्पणी', specialRequirements: 'विशेष आवश्यकताहरू', cancel: 'रद्द', saving: 'सेभ हुँदै…', saveChanges: 'परिवर्तन सेभ गर्नुहोस्', createCustomer: 'ग्राहक सिर्जना गर्नुहोस्' },
      card: { created: 'बनेको मिति', orders: 'अर्डर', spent: 'खर्च', last: 'अन्तिम', edit: 'सम्पादन' }
    }
  } },
  tl: { translation: {
    Language: 'Wika',
    layout: { brandName: 'INCH', brandTag: 'Tailoring SaaS', roleOwner: 'May-ari ng Negosyo 👑', roleStaff: 'Staff' },
    nav: { dashboard: 'Dashboard', customers: 'Mga Customer', orders: 'Mga Order', 'job cards': 'Job Cards', invoices: 'Mga Invoice', inventory: 'Imbentaryo', staff: 'Staff', expenses: 'Gastos', reports: 'Mga Ulat', messages: 'Mga Mensahe', 'public profile': 'Pampublikong Profile', settings: 'Mga Setting' },
    settings: { title: 'Mga Setting', subtitle: 'I-configure ang negosyo, account, at mga preference.', sectionsAriaLabel: 'Mga seksyon ng setting', tabs: { business: 'Negosyo', user: 'User Settings', invoice: 'Invoice', notifications: 'Notipikasyon', security: 'Seguridad', appearance: 'Hitsura' } },
    business: { title: 'Impormasyon ng Negosyo', subtitle: 'Pamahalaan ang detalye at branding.', staffInfo: 'Tanging ang may-ari lang ang puwedeng mag-edit.', businessId: 'Business ID', businessLogo: 'Logo ng Negosyo', uploading: 'Nag-a-upload…', uploadLogo: 'I-upload ang Logo', businessName: 'Pangalan ng Negosyo', businessNamePlaceholder: 'Pangalan ng kumpanya', businessNameLocked: 'Kinokontrol ng admin', ownerName: 'Pangalan ng May-ari', ownerNamePlaceholder: 'Buong pangalan', businessPhone: 'Telepono ng Negosyo', businessPhonePlaceholder: 'Hal. +63 900 000 0000', businessEmail: 'Email ng Negosyo', businessEmailPlaceholder: 'name@company.com', businessEmailLocked: 'Kinokontrol ng admin', businessAddress: 'Address ng Negosyo', businessAddressPlaceholder: 'Kalsada, Lungsod, Bansa', saveBusinessInfo: 'I-save ang Impormasyon', saving: 'Sini-save…', savedNotice: 'Na-save ✓', logoSaved: 'Nai-update ang logo ✓' },
    attendance: { title: 'Attendance at Shift Rules', subtitle: 'Itakda ang standard workday at break policy.', standardShiftLength: 'Karaniwang minuto bawat araw', maxBreaksPerDay: 'Pinakamadaming break bawat araw', minutesPerBreak: 'Minuto bawat break', saveAttendanceRules: 'I-save ang mga patakaran', savedNotice: 'Na-save ang mga patakaran ✓' },
    invoice: { title: 'Mga Setting ng Invoice', subtitle: 'I-set ang default at numbering.', taxRate: 'Tax rate (%)', currency: 'Currency', autoGenerate: 'Awtomatikong gumawa ng invoice numbers', paymentTerms: 'Payment terms', paymentTermsPlaceholder: 'Hal. Net 30', invoiceFooter: 'Invoice footer', invoiceFooterPlaceholder: 'Mensahe sa ibaba ng invoice', saveInvoiceSettings: 'I-save ang mga setting' },
    notifications: { title: 'Notipikasyon', subtitle: 'Piliin kung paano ka aabisuhan.', emailNotifications: 'Email notipikasyon', emailNotificationsDescription: 'Tumanggap ng updates sa email.', pushNotifications: 'Push notipikasyon', pushNotificationsDescription: 'Tumanggap ng in-app at device push.', saveNotificationSettings: 'I-save ang mga notipikasyon' },
    security: { title: 'Seguridad', subtitle: 'Pamahalaan ang seguridad at privacy.', accountInformation: 'Impormasyon ng account', passwordManagement: 'Pamamahala ng password', passwordManagementDescription: 'Gumamit ng malakas na password. Maaaring i-reset dito.', resetPassword: 'I-reset ang password', downloadAccountData: 'I-download ang data', downloadAccountDataDescription: 'I-export ang kopya ng personal na data.' },
    appearance: { title: 'Hitsura', subtitle: 'I-customize ang theme, gradient, at glow.', gradientAngle: 'Anggulo ng gradient', gradientAngleDescription: 'Ayusin ang anggulo ng brand gradient.', glow: 'Glow', glowDescription: 'I-tune ang glow o pumili ng custom na kulay.', matchTheme: 'Tugma sa theme', custom: 'Custom', depth: 'Lalim', customGradient: 'Custom gradient', customGradientDescription: 'Piliin ang mga kulay.', from: 'Mula', to: 'Hanggang', solidColor: 'Solid color accents', solidColorDescription: 'Pumili ng iisang kulay.', themeChangesApplyInstantly: 'Agad na naa-apply ang mga pagbabago.', saveAppearance: 'I-save ang hitsura', saving: 'Sini-save…', resetToDefault: 'I-reset sa default', savedNotice: 'Na-save ✓', saveFailed: 'Nabigong mag-save' },
    userSettings: {
      title: 'Mga Setting ng User',
      subtitle: 'I-update ang iyong personal na mga setting para sa account na ito.',
      userAvatar: 'Avatar ng User',
      uploading: 'Nag-a-upload…',
      uploadAvatar: 'I-upload ang Avatar',
      displayName: 'Display Name',
      language: 'Wika',
      changeEmail: 'Palitan ang Email',
      updateEmail: 'I-update ang Email',
      newPassword: 'Bagong Password',
      confirmPassword: 'Kumpirmahin ang Password',
      saving: 'Sini-save…',
      saveUserSettings: 'I-save ang Mga Setting ng User',
      changePassword: 'Palitan ang Password',
      placeholderName: 'Iyong pangalan',
      placeholderEmail: 'you@example.com',
      savedNotice: 'Na-save ang mga setting ng user ✓',
      emailUpdateInitiated: 'Sinimulan ang pag-update ng email. Suriin ang iyong inbox para kumpirmahin.',
      passwordChanged: 'Napalitan ang password ✓',
      uploadAvatarSuccess: 'Na-upload ang avatar ✓'
    },
    common: {
      loading: 'Naglo-load…',
      signOut: 'Mag-sign out',
      signingOut: 'Nag-sign out…',
      expandSidebar: 'Palawakin ang sidebar',
      collapseSidebar: 'I-collapse ang sidebar',
      viewAll: 'Tingnan Lahat',
      createFirstOrder: 'Gumawa ng Unang Order',
      noOrdersYet: 'Wala pang mga order',
      quickActions: 'Mabilisang Aksyon',
      recordExpense: 'Irekord ang Gastos',
      createJobCard: 'Gumawa ng Job Card',
      addCustomer: 'Magdagdag ng Customer',
      newOrder: 'Bagong Order',
      actions: { save: 'I-save', cancel: 'Kanselahin', edit: 'I-edit', delete: 'I-delete', update: 'I-update', search: 'Hanapin', filter: 'I-filter', export: 'I-export', import: 'I-import', upload: 'I-upload', download: 'I-download', print: 'I-print', apply: 'I-apply', reset: 'I-reset', close: 'Isara', ok: 'OK', yes: 'Oo', no: 'Hindi', add: 'Magdagdag', remove: 'Alisin' },
      feedback: { saved: 'Na-save ✓', updated: 'Na-update ✓', deleted: 'Na-delete ✓', errorSaving: 'Error sa pagsave', errorLoading: 'Error sa pag-load', areYouSure: 'Sigurado ka?', confirmDelete: 'Kumpirmahin ang pag-delete?', required: 'Kinakailangang field', invalidEmail: 'Di-wastong email' }
    },
    dashboard: {
      lowStockAlerts: 'Mga Alerto sa Mababa ang Stock',
      allFabricsStocked: 'Lahat ng tela ay may stock',
      viewInventory: 'Tingnan ang Imbentaryo',
      recentOrders: 'Mga Kamakailang Order',
      todaysActivity: 'Aktibidad Ngayon',
      nowOrders: 'Mga Order Ngayon',
      ordersReady: 'Handang Order',
      inProgress: 'Isinasagawa',
      totalRevenue: 'Kabuuang Kita',
      totalCustomers: 'Kabuuang Customer',
      totalOrders: 'Kabuuang Order',
      lowStockItems: 'Mga Item na Mababa ang Stock',
      pendingOrders: 'Nakabinbing Order',
      businessBadge: 'Negosyo',
      idLabel: 'ID',
      welcomeToBrand: 'Maligayang pagdating sa INCH',
      welcomeBusinessToBrand: 'Maligayang pagdating {{name}} sa INCH',
      staffId: 'StaffID'
    },
    customers: {
      title: 'Mga Customer',
      subtitle: 'Pamahalaan ang iyong mga customer.',
      searchPlaceholder: 'Maghanap sa pangalan o telepono…',
      addCustomer: '+ Magdagdag ng Customer',
      loading: 'Naglo-load…',
      empty: 'Walang nahanap na customer',
      modal: { addTitle: 'Magdagdag ng Customer', editTitle: 'I-edit ang Customer', close: 'Isara' },
      form: { basics: 'Mga Pangunahing Impormasyon', name: 'Pangalan', phone: 'Telepono', email: 'Email', address: 'Address', nameRequired: 'Kinakailangan ang pangalan', nameTooShort: 'Dapat hindi bababa sa 2 titik ang pangalan', phoneRequired: 'Kinakailangan ang telepono', invalidEmail: 'Di-wastong email', measurements: 'Mga Sukat', visualMeasurements: 'Biswal na Sukat', addLabel: 'Magdagdag ng label', moveBuiltIns: 'Ilipat ang built-ins', clearCustomLabels: 'I-clear ang custom labels', customMeasurements: 'Custom na sukat', add: '+ Magdagdag', remove: 'Alisin', value: 'Halaga', unit: 'Yunit', cm: 'cm', inch: 'in', measure: { chest: 'Dibdib', waist: 'Baywang', hips: 'Balakang', shoulders: 'Balikat', sleeve_length: 'Haba ng manggas', neck: 'Leeg', inseam: 'Inseam', outseam: 'Outseam', thigh: 'Hita' }, preferences: 'Mga Kagustuhan', preferredFabric: 'Pin prefer na tela', styleNotes: 'Mga Tala sa Estilo', specialRequirements: 'Espesyal na Kahilingan', cancel: 'Kanselahin', saving: 'Sini-save…', saveChanges: 'I-save ang mga pagbabago', createCustomer: 'Gumawa ng Customer' },
      card: { created: 'Nagawa', orders: 'Mga Order', spent: 'Gastos', last: 'Huli', edit: 'I-edit' }
    }
  } },
  bn: { translation: {
    Language: 'ভাষা',
    layout: { brandName: 'INCH', brandTag: 'টেইলরিং SaaS', roleOwner: 'ব্যবসার মালিক 👑', roleStaff: 'স্টাফ' },
    nav: { dashboard: 'ড্যাশবোর্ড', customers: 'কাস্টমার', orders: 'অর্ডার', 'job cards': 'জব কার্ড', invoices: 'ইনভয়েস', inventory: 'ইনভেন্টরি', staff: 'স্টাফ', expenses: 'খরচ', reports: 'রিপোর্ট', messages: 'বার্তা', 'public profile': 'পাবলিক প্রোফাইল', settings: 'সেটিংস' },
    settings: { title: 'সেটিংস', subtitle: 'আপনার ব্যবসা, অ্যাকাউন্ট ও পছন্দ কনফিগার করুন।', sectionsAriaLabel: 'সেটিংস সেকশন', tabs: { business: 'ব্যবসা', user: 'ইউজার সেটিংস', invoice: 'ইনভয়েস', notifications: 'নোটিফিকেশন', security: 'নিরাপত্তা', appearance: 'চেহারা' } },
    business: { title: 'ব্যবসার তথ্য', subtitle: 'কোম্পানির বিবরণ ও ব্র্যান্ডিং পরিচালনা করুন।', staffInfo: 'শুধু মালিক এসব ফিল্ড সম্পাদনা করতে পারেন।', businessId: 'ব্যবসা আইডি', businessLogo: 'ব্যবসার লোগো', uploading: 'আপলোড হচ্ছে…', uploadLogo: 'লোগো আপলোড', businessName: 'ব্যবসার নাম', businessNamePlaceholder: 'আপনার ব্যবসার নাম', businessNameLocked: 'অ্যাডমিন দ্বারা নিয়ন্ত্রিত', ownerName: 'মালিকের নাম', ownerNamePlaceholder: 'পুরো নাম', businessPhone: 'ব্যবসার ফোন', businessPhonePlaceholder: 'যেমন +880 1700 000000', businessEmail: 'ব্যবসার ইমেল', businessEmailPlaceholder: 'name@company.com', businessEmailLocked: 'অ্যাডমিন দ্বারা নিয়ন্ত্রিত', businessAddress: 'ব্যবসার ঠিকানা', businessAddressPlaceholder: 'রাস্তা, শহর, দেশ', saveBusinessInfo: 'ব্যবসার তথ্য সংরক্ষণ', saving: 'সংরক্ষণ হচ্ছে…', savedNotice: 'সংরক্ষিত ✓', logoSaved: 'লোগো আপডেট হয়েছে ✓' },
    attendance: { title: 'উপস্থিতি ও শিফট নীতিমালা', subtitle: 'মানক কর্মদিবস ও বিরতি নীতি নির্ধারণ করুন।', standardShiftLength: 'প্রতিদিন মানক মিনিট', maxBreaksPerDay: 'প্রতিদিন সর্বোচ্চ বিরতি', minutesPerBreak: 'প্রতি বিরতিতে মিনিট', saveAttendanceRules: 'নীতিমালা সংরক্ষণ', savedNotice: 'নীতিমালা সংরক্ষিত ✓' },
    invoice: { title: 'ইনভয়েস সেটিংস', subtitle: 'ইনভয়েস ডিফল্ট ও নম্বরিং নির্ধারণ করুন।', taxRate: 'ট্যাক্স হার (%)', currency: 'কারেন্সি', autoGenerate: 'ইনভয়েস নম্বর স্বয়ংক্রিয়ভাবে তৈরি', paymentTerms: 'পরিশোধের শর্ত', paymentTermsPlaceholder: 'যেমন Net 30', invoiceFooter: 'ইনভয়েস ফুটার', invoiceFooterPlaceholder: 'ইনভয়েসের নিচে দেখানো বার্তা', saveInvoiceSettings: 'ইনভয়েস সেটিংস সংরক্ষণ' },
    notifications: { title: 'নোটিফিকেশন', subtitle: 'আপনি কিভাবে নোটিফাইড হতে চান নির্বাচন করুন।', emailNotifications: 'ইমেল নোটিফিকেশন', emailNotificationsDescription: 'ইমেলে আপডেট ও অ্যালার্ট পান।', pushNotifications: 'পুশ নোটিফিকেশন', pushNotificationsDescription: 'অ্যাপ ও ডিভাইসে পুশ নোটিফিকেশন পান।', saveNotificationSettings: 'নোটিফিকেশন সংরক্ষণ' },
    security: { title: 'নিরাপত্তা', subtitle: 'অ্যাকাউন্ট নিরাপত্তা ও প্রাইভেসি ম্যানেজ করুন।', accountInformation: 'অ্যাকাউন্ট তথ্য', passwordManagement: 'পাসওয়ার্ড ব্যবস্থাপনা', passwordManagementDescription: 'শক্তিশালী অনন্য পাসওয়ার্ড ব্যবহার করুন।', resetPassword: 'পাসওয়ার্ড রিসেট', downloadAccountData: 'অ্যাকাউন্ট ডাটা ডাউনলোড', downloadAccountDataDescription: 'আপনার ব্যক্তিগত ডাটা এক্সপোর্ট করুন।' },
    appearance: { title: 'চেহারা', subtitle: 'থিম, গ্রেডিয়েন্ট ও গ্লো কাস্টমাইজ করুন।', gradientAngle: 'গ্রেডিয়েন্ট কোণ', gradientAngleDescription: 'ব্র্যান্ড গ্রেডিয়েন্টের কোণ নির্ধারণ করুন।', glow: 'গ্লো', glowDescription: 'থিমের সাথে মিলান বা কাস্টম রঙ বাছুন।', matchTheme: 'থিম মিল', custom: 'কাস্টম', depth: 'গভীরতা', customGradient: 'কাস্টম গ্রেডিয়েন্ট', customGradientDescription: 'নিজের রঙ বেছে নিন।', from: 'থেকে', to: 'পর্যন্ত', solidColor: 'সলিড রঙ অ্যাকসেন্ট', solidColorDescription: 'একটি রঙ বেছে নিন।', themeChangesApplyInstantly: 'থিম পরিবর্তন সঙ্গে সঙ্গে কার্যকর।', saveAppearance: 'চেহারা সংরক্ষণ', saving: 'সংরক্ষণ হচ্ছে…', resetToDefault: 'ডিফল্টে রিসেট', savedNotice: 'সংরক্ষিত ✓', saveFailed: 'সংরক্ষণ ব্যর্থ' },
    userSettings: {
      title: 'ব্যবহারকারী সেটিংস',
      subtitle: 'এই অ্যাকাউন্টের জন্য আপনার ব্যক্তিগত সেটিংস আপডেট করুন।',
      userAvatar: 'ব্যবহারকারীর অ্যাভাটার',
      uploading: 'আপলোড হচ্ছে…',
      uploadAvatar: 'অ্যাভাটার আপলোড করুন',
      displayName: 'প্রদর্শন নাম',
      language: 'ভাষা',
      changeEmail: 'ইমেল পরিবর্তন করুন',
      updateEmail: 'ইমেল আপডেট করুন',
      newPassword: 'নতুন পাসওয়ার্ড',
      confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
      saving: 'সংরক্ষণ করা হচ্ছে…',
      saveUserSettings: 'ব্যবহারকারী সেটিংস সংরক্ষণ করুন',
      changePassword: 'পাসওয়ার্ড পরিবর্তন করুন',
      placeholderName: 'আপনার নাম',
      placeholderEmail: 'you@example.com',
      savedNotice: 'ব্যবহারকারী সেটিংস সংরক্ষিত ✓',
      emailUpdateInitiated: 'ইমেল আপডেট শুরু হয়েছে। নিশ্চিত করতে ইনবক্স চেক করুন।',
      passwordChanged: 'পাসওয়ার্ড পরিবর্তিত হয়েছে ✓',
      uploadAvatarSuccess: 'অ্যাভাটার আপলোড হয়েছে ✓'
    },
    common: {
      loading: 'লোড হচ্ছে…',
      signOut: 'সাইন আউট',
      signingOut: 'সাইন আউট হচ্ছে…',
      expandSidebar: 'সাইডবার প্রসারিত করুন',
      collapseSidebar: 'সাইডবার সংকুচিত করুন',
      viewAll: 'সকল দেখুন',
      createFirstOrder: 'প্রথম অর্ডার তৈরি করুন',
      noOrdersYet: 'এখনও কোনো অর্ডার নেই',
      quickActions: 'দ্রুত অ্যাকশন',
      recordExpense: 'খরচ রেকর্ড করুন',
      createJobCard: 'জব কার্ড তৈরি করুন',
      addCustomer: 'কাস্টমার যোগ করুন',
      newOrder: 'নতুন অর্ডার',
      actions: { save: 'সংরক্ষণ', cancel: 'বাতিল', edit: 'সম্পাদনা', delete: 'মুছে ফেলুন', update: 'আপডেট', search: 'খোঁজ', filter: 'ফিল্টার', export: 'রপ্তানি', import: 'আমদানি', upload: 'আপলোড', download: 'ডাউনলোড', print: 'প্রিন্ট', apply: 'প্রয়োগ', reset: 'রিসেট', close: 'বন্ধ', ok: 'ঠিক আছে', yes: 'হ্যাঁ', no: 'না', add: 'যোগ করুন', remove: 'অপসারণ' },
      feedback: { saved: 'সংরক্ষিত ✓', updated: 'আপডেট হয়েছে ✓', deleted: 'মুছে ফেলা হয়েছে ✓', errorSaving: 'সংরক্ষণে ত্রুটি', errorLoading: 'লোডে ত্রুটি', areYouSure: 'আপনি কি নিশ্চিত?', confirmDelete: 'মুছে ফেলতে নিশ্চিত?', required: 'আবশ্যক ঘর', invalidEmail: 'অবৈধ ইমেল' }
    },
    dashboard: {
      lowStockAlerts: 'স্টক কম নোটিশ',
      allFabricsStocked: 'সব ফ্যাব্রিক স্টকে আছে',
      viewInventory: 'ইনভেন্টরি দেখুন',
      recentOrders: 'সাম্প্রতিক অর্ডার',
      todaysActivity: 'আজকের কার্যক্রম',
      nowOrders: 'বর্তমান অর্ডার',
      ordersReady: 'অর্ডার প্রস্তুত',
      inProgress: 'চলমান',
      totalRevenue: 'মোট রাজস্ব',
      totalCustomers: 'মোট কাস্টমার',
      totalOrders: 'মোট অর্ডার',
      lowStockItems: 'স্টক কম আইটেম',
      pendingOrders: 'মুলতুবি অর্ডার',
      businessBadge: 'ব্যবসা',
      idLabel: 'আইডি',
      welcomeToBrand: 'INCH-এ স্বাগতম',
      welcomeBusinessToBrand: 'স্বাগতম {{name}} INCH-এ',
      staffId: 'স্টাফ আইডি'
    },
    customers: {
      title: 'কাস্টমার',
      subtitle: 'আপনার কাস্টমার পরিচালনা করুন।',
      searchPlaceholder: 'নাম বা ফোনে খুঁজুন…',
      addCustomer: '+ কাস্টমার যোগ করুন',
      loading: 'লোড হচ্ছে…',
      empty: 'কোনো কাস্টমার পাওয়া যায়নি',
      modal: { addTitle: 'কাস্টমার যোগ করুন', editTitle: 'কাস্টমার সম্পাদনা', close: 'বন্ধ' },
      form: { basics: 'বেসিক', name: 'নাম', phone: 'ফোন', email: 'ইমেল', address: 'ঠিকানা', nameRequired: 'নাম প্রয়োজন', nameTooShort: 'নাম অন্তত ২ অক্ষরের হতে হবে', phoneRequired: 'ফোন প্রয়োজন', invalidEmail: 'অবৈধ ইমেল', measurements: 'পরিমাপ', visualMeasurements: 'ভিজ্যুয়াল পরিমাপ', addLabel: 'লেবেল যোগ করুন', moveBuiltIns: 'বিল্ট-ইন সরান', clearCustomLabels: 'কাস্টম লেবেল মুছুন', customMeasurements: 'কাস্টম পরিমাপ', add: '+ যোগ করুন', remove: 'অপসারণ', value: 'মান', unit: 'একক', cm: 'সেমি', inch: 'ইঞ্চি', measure: { chest: 'বুক', waist: 'কোমর', hips: 'হিপ', shoulders: 'কাঁধ', sleeve_length: 'হাতা লম্বা', neck: 'গলা', inseam: 'ইনসিম', outseam: 'আউটসিম', thigh: 'উরু' }, preferences: 'পছন্দ', preferredFabric: 'পছন্দের কাপড়', styleNotes: 'স্টাইল নোট', specialRequirements: 'বিশেষ প্রয়োজনীয়তা', cancel: 'বাতিল', saving: 'সংরক্ষণ হচ্ছে…', saveChanges: 'পরিবর্তন সংরক্ষণ', createCustomer: 'কাস্টমার তৈরি করুন' },
      card: { created: 'তৈরি', orders: 'অর্ডার', spent: 'খরচ', last: 'সর্বশেষ', edit: 'সম্পাদনা' }
    }
  } },
  ur: { translation: {
    Language: 'زبان',
    layout: { brandName: 'INCH', brandTag: 'ٹیلرنگ SaaS', roleOwner: 'بزنس اونر 👑', roleStaff: 'اسٹاف' },
    nav: { dashboard: 'ڈیش بورڈ', customers: 'کسٹمرز', orders: 'آرڈر', 'job cards': 'جاب کارڈز', invoices: 'انوائسز', inventory: 'انوینٹری', staff: 'اسٹاف', expenses: 'اخراجات', reports: 'رپورٹس', messages: 'پیغامات', 'public profile': 'عوامی پروفائل', settings: 'سیٹنگز' },
    settings: { title: 'سیٹنگز', subtitle: 'اپنے کاروبار، اکاؤنٹ اور ترجیحات ترتیب دیں۔', sectionsAriaLabel: 'سیٹنگز کے حصے', tabs: { business: 'بزنس', user: 'یوزر سیٹنگز', invoice: 'انوائس', notifications: 'اعلانات', security: 'سکیورٹی', appearance: 'ظاہری شکل' } },
    business: { title: 'بزنس معلومات', subtitle: 'کمپنی کی تفصیلات اور برانڈنگ کا نظم کریں۔', staffInfo: 'صرف مالک ان فیلڈز میں ترمیم کر سکتا ہے۔', businessId: 'بزنس آئی ڈی', businessLogo: 'بزنس لوگو', uploading: 'اپ لوڈ ہو رہا ہے…', uploadLogo: 'لوگو اپ لوڈ کریں', businessName: 'بزنس نام', businessNamePlaceholder: 'آپ کے کاروبار کا نام', businessNameLocked: 'بزنس نام ایڈمن کے ذریعے کنٹرول ہوتا ہے', ownerName: 'مالک کا نام', ownerNamePlaceholder: 'پورا نام', businessPhone: 'بزنس فون', businessPhonePlaceholder: 'مثال: +965 555 12345', businessEmail: 'بزنس ای میل', businessEmailPlaceholder: 'name@company.com', businessEmailLocked: 'بزنس ای میل ایڈمن کے ذریعے کنٹرول ہوتا ہے', businessAddress: 'بزنس پتہ', businessAddressPlaceholder: 'گلی، شہر، ملک', saveBusinessInfo: 'بزنس معلومات محفوظ کریں', saving: 'محفوظ کیا جا رہا ہے…', savedNotice: 'محفوظ ہوگیا ✓', logoSaved: 'لوگو اپ ڈیٹ ہوگیا ✓' },
    attendance: { title: 'حاضری اور شفট قواعد', subtitle: 'معیاری ورک ڈے اور بریک پالیسی طے کریں۔', standardShiftLength: 'ایک دن کے معیاری منٹس', maxBreaksPerDay: 'روزانہ زیادہ سے زیادہ بریک', minutesPerBreak: 'فی بریک منٹس', saveAttendanceRules: 'حاضری قواعد محفوظ کریں', savedNotice: 'حاضری قواعد محفوظ ہوگئے ✓' },
    invoice: { title: 'انوائس سیٹنگز', subtitle: 'انوائس ڈیفالٹس اور نمبرنگ سیٹ کریں۔', taxRate: 'ٹیکس ریٹ (%)', currency: 'کرنسی', autoGenerate: 'انوائس نمبر خودکار بنائیں', paymentTerms: 'ادائیگی کی شرائط', paymentTermsPlaceholder: 'مثال: نیٹ 30', invoiceFooter: 'انوائس فوٹر', invoiceFooterPlaceholder: 'انوائس کے نیچے دکھایا جانے والا پیغام', saveInvoiceSettings: 'انوائس سیٹنگز محفوظ کریں' },
    notifications: { title: 'اعلانات', subtitle: 'منتخب کریں کہ اطلاع کیسے حاصل کرنی ہے۔', emailNotifications: 'ای میل اعلانات', emailNotificationsDescription: 'ای میل کے ذریعے اپ ڈیٹس اور الرٹس حاصل کریں۔', pushNotifications: 'پش اعلانات', pushNotificationsDescription: 'ایپ اور ڈیوائس پر پش اعلانات حاصل کریں۔', saveNotificationSettings: 'اعلانات محفوظ کریں' },
    security: { title: 'سکیورٹی', subtitle: 'اکاؤنٹ سکیورٹی اور پرائیویسی کا نظم کریں۔', accountInformation: 'اکاؤنٹ معلومات', passwordManagement: 'پاس ورڈ مینجمنٹ', passwordManagementDescription: 'طاقتور اور منفرد پاس ورڈ استعمال کریں۔', resetPassword: 'پاس ورڈ ری سیٹ', downloadAccountData: 'اکاؤنٹ ڈیٹا ڈاؤن لوڈ', downloadAccountDataDescription: 'اپنے ذاتی ڈیٹا کی کاپی ایکسپورٹ کریں۔' },
    appearance: { title: 'ظاہری شکل', subtitle: 'تھیم، گریڈینٹ اور گلو اپنی مرضی سے بنائیں۔', gradientAngle: 'گریڈینٹ زاویہ', gradientAngleDescription: 'برانڈ گریڈینٹ کا زاویہ ایڈجسٹ کریں۔', glow: 'گلو', glowDescription: 'تھیم سے میچ کریں یا کسٹم رنگ منتخب کریں۔', matchTheme: 'تھیم سے میچ', custom: 'کسٹم', depth: 'گہرائی', customGradient: 'کسٹم گریڈینٹ', customGradientDescription: 'اپنے رنگ منتخب کریں۔', from: 'سے', to: 'تک', solidColor: 'ٹھوس رنگ', solidColorDescription: 'ایک ہی رنگ منتخب کریں۔', themeChangesApplyInstantly: 'تھیم میں تبدیلی فوری طور پر لاگو ہوتی ہے۔', saveAppearance: 'ظاہری شکل محفوظ کریں', saving: 'محفوظ کیا جا رہا ہے…', resetToDefault: 'ڈیفالٹ پر ری سیٹ', savedNotice: 'محفوظ ہوگیا ✓', saveFailed: 'محفوظ کرنے میں ناکامی' },
    userSettings: {
      title: 'صارف کی ترتیبات',
      subtitle: 'اس اکاؤنٹ کے لیے اپنی ذاتی ترتیبات اپ ڈیٹ کریں۔',
      userAvatar: 'صارف کی تصویر',
      uploading: 'اپ لوڈ ہو رہا ہے…',
      uploadAvatar: 'تصویر اپ لوڈ کریں',
      displayName: 'نمایشی نام',
      language: 'زبان',
      changeEmail: 'ای میل تبدیل کریں',
      updateEmail: 'ای میل اپ ڈیٹ کریں',
      newPassword: 'نیا پاس ورڈ',
      confirmPassword: 'پاس ورڈ کی تصدیق کریں',
      saving: 'محفوظ کیا جا رہا ہے…',
      saveUserSettings: 'صارف کی ترتیبات محفوظ کریں',
      changePassword: 'پاس ورڈ تبدیل کریں',
      placeholderName: 'آپ کا نام',
      placeholderEmail: 'you@example.com',
      savedNotice: 'صارف کی ترتیبات محفوظ کر لی گئیں ✓',
      emailUpdateInitiated: 'ای میل اپ ڈیٹ شروع کر دی گئی ہے۔ تصدیق کے لیے اپنا ان باکس چیک کریں۔',
      passwordChanged: 'پاس ورڈ تبدیل ہو گیا ✓',
      uploadAvatarSuccess: 'تصویر اپ لوڈ ہو گئی ✓'
    },
    common: {
      loading: 'لوڈ ہو رہا ہے…',
      signOut: 'سائن آؤٹ',
      signingOut: 'سائن آؤٹ ہو رہا ہے…',
      expandSidebar: 'سائڈبار بڑا کریں',
      collapseSidebar: 'سائڈبار سمیٹیں',
      viewAll: 'سب دیکھیں',
      createFirstOrder: 'پہلا آرڈر بنائیں',
      noOrdersYet: 'ابھی تک کوئی آرڈر نہیں',
      quickActions: 'فوری کارروائیاں',
      recordExpense: 'خرچ ریکارڈ کریں',
      createJobCard: 'جاب کارڈ بنائیں',
      addCustomer: 'کسٹمر شامل کریں',
      newOrder: 'نیا آرڈر',
      actions: { save: 'محفوظ کریں', cancel: 'منسوخ کریں', edit: 'ترمیم', delete: 'حذف', update: 'اپ ڈیٹ', search: 'تلاش', filter: 'فلٹر', export: 'ایکسپورٹ', import: 'امپورٹ', upload: 'اپ لوڈ', download: 'ڈاؤن لوڈ', print: 'پرنٹ', apply: 'لاگو کریں', reset: 'ری سیٹ', close: 'بند کریں', ok: 'ٹھیک', yes: 'ہاں', no: 'نہیں', add: 'شامل کریں', remove: 'ہٹائیں' },
      feedback: { saved: 'محفوظ ہوگیا ✓', updated: 'اپ ڈیٹ ہوگیا ✓', deleted: 'حذف ہوگیا ✓', errorSaving: 'محفوظ کرنے میں خرابی', errorLoading: 'لوڈ کرنے میں خرابی', areYouSure: 'کیا آپ پُر اعتماد ہیں؟', confirmDelete: 'حذف کی تصدیق؟', required: 'لازمی خانہ', invalidEmail: 'غیر درست ای میل' }
    },
    dashboard: {
      lowStockAlerts: 'کم اسٹاک انتباہ',
      allFabricsStocked: 'تمام فیبرکس دستیاب ہیں',
      viewInventory: 'انوینٹری دیکھیں',
      recentOrders: 'حالیہ آرڈر',
      todaysActivity: 'آج کی سرگرمی',
      nowOrders: 'موجودہ آرڈر',
      ordersReady: 'آرڈر تیار',
      inProgress: 'جاری ہے',
      totalRevenue: 'کل آمدنی',
      totalCustomers: 'کل کسٹمرز',
      totalOrders: 'کل آرڈر',
      lowStockItems: 'کم اسٹاک آئٹمز',
      pendingOrders: 'زیرِ التواء آرڈر',
      businessBadge: 'بزنس',
      idLabel: 'شناخت',
      welcomeToBrand: 'INCH میں خوش آمدید',
      welcomeBusinessToBrand: 'خوش آمدید {{name}} INCH میں',
      staffId: 'اسٹاف آئی ڈی'
    },
    customers: {
      title: 'کسٹمرز',
      subtitle: 'اپنے کسٹمرز کا نظم کریں۔',
      searchPlaceholder: 'نام یا فون سے تلاش…',
      addCustomer: '+ کسٹمر شامل کریں',
      loading: 'لوڈ ہو رہا ہے…',
      empty: 'کوئی کسٹمر نہیں ملا',
      modal: { addTitle: 'کسٹمر شامل کریں', editTitle: 'کسٹمر میں ترمیم', close: 'بند کریں' },
      form: { basics: 'بنیادی معلومات', name: 'نام', phone: 'فون', email: 'ای میل', address: 'پتہ', nameRequired: 'نام ضروری ہے', nameTooShort: 'نام کم از کم 2 حروف کا ہونا چاہیے', phoneRequired: 'فون ضروری ہے', invalidEmail: 'غیر درست ای میل', measurements: 'ناب و طول', visualMeasurements: 'بصری ناب و طول', addLabel: 'لیبل شامل کریں', moveBuiltIns: 'بلٹ-ان منتقل کریں', clearCustomLabels: 'کسٹم لیبل صاف کریں', customMeasurements: 'کسٹم ناب و طول', add: '+ شامل کریں', remove: 'ہٹائیں', value: 'قدر', unit: 'یکائی', cm: 'سم', inch: 'انچ', measure: { chest: 'چھاتی', waist: 'کمر', hips: 'ہپس', shoulders: 'کندھے', sleeve_length: 'آستین کی لمبائی', neck: 'گردن', inseam: 'ان سیم', outseam: 'آؤٹ سیم', thigh: 'ران' }, preferences: 'ترجیحات', preferredFabric: 'پسندیدہ کپڑا', styleNotes: 'اسٹائل نوٹس', specialRequirements: 'خصوصی ضروریات', cancel: 'منسوخ کریں', saving: 'محفوظ کیا جا رہا ہے…', saveChanges: 'تبدیلیاں محفوظ کریں', createCustomer: 'کسٹمر بنائیں' },
      card: { created: 'تخلیق', orders: 'آرڈر', spent: 'خرچ', last: 'آخری', edit: 'ترمیم' }
    }
  } },
}

if (!i18next.isInitialized) {
  i18next
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
      resources,
      fallbackLng: 'en',
      supportedLngs: ['en', 'ar', 'hi', 'ne', 'tl', 'bn', 'ur'],
      detection: {
        order: ['localStorage', 'navigator', 'htmlTag'],
        caches: ['localStorage'],
      },
      interpolation: { escapeValue: false },
    })
    .then(() => {
      const lng = i18next.language || 'en'
      document.documentElement.setAttribute('lang', lng)
      document.documentElement.setAttribute('dir', i18next.dir(lng))
    })
}

// Keep dir/lang in sync when language changes
i18next.on('languageChanged', (lng) => {
  document.documentElement.setAttribute('lang', lng)
  document.documentElement.setAttribute('dir', i18next.dir(lng))
})

// Expose i18next for runtime language switching in settings
if (typeof window !== 'undefined') {
  window.i18next = i18next
}

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <ErrorBoundary>
      <App />
    </ErrorBoundary>
  </StrictMode>,
)
